version: '3.9'

services:
  mysql:
    image: mysql:8.0 
    container_name: mysql_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword 
      MYSQL_DATABASE: mydatabase        
      MYSQL_USER: myuser               
      MYSQL_PASSWORD: mypassword       
    ports:
      - "3306:3306" 
    volumes:
      - mysql_data:/var/lib/mysql       # Armazena os dados do MySQL em um volume persistente

volumes:
  mysql_data:
    driver: local
